name: Build & deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore
        run: dotnet restore Backend/MoviePerspectives.csproj

      - name: Build
        run: dotnet build --configuration Release Backend/MoviePerspectives.csproj

      - name: Publish
        run: dotnet publish --configuration Release --output publish_output Backend/MoviePerspectives.csproj

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MOVIE-PERSPECTIVES'
          slot-name: 'production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish_output
