name: Build and deploy ASP.Net Core app to Azure Web App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore ./Backend/MoviePerspectives.csproj

      - name: Build
        run: dotnet build --configuration Release ./Backend/MoviePerspectives.csproj

      - name: Publish
        run: dotnet publish --configuration Release --output publish ./Backend/MoviePerspectives.csproj

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: Movie-Perspectives        
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: publish
